### ISSUE TITLE
On the adoption of netplan for network configuration

### ISSUE THREAD

**Issue by antoan** [fetchrobotics/fetch_robots#58]
I would be very grateful if you could spare some thoughts on why netplan was chosen over the older ifupdown method, if it made things, or if the design goals of netplan met your expectations?

Cheers

**Comment by moriarty** [comment]
Other than the reason that on Ubuntu 17.10+ Netplan is the default?

https://ubuntu.com/blog/ubuntu-bionic-netplan

https://wiki.ubuntu.com/MigratingToNetplan

**Comment by erelson** [comment]
Howdy! I implemented that change with the rough thought in mind of, "this is the new default, and adapting it will be the least painful approach."*  It works well for our needs.  I personally find its config files a bit more approachable, too.

Off the top of my head I feel the following couple assumptions are probably pretty valid: (1) Most users don't need to change configuration often; (2) anyone needing more complex things will also be able to figure out how to make that happen.

More recently for other setups where we're switching between multiple network configurations, I've been commenting out the netplan rules for a given interface (so that netplan doesn't manage the interface), and using saved NetworkManager connection definitions that are easy to switch between.

*For interface naming, I stubbornly have been sticking to the old-style wlan0/eth0 naming, and haven't regretted that decision.

**Comment by antoan** [comment]
@erelson

Thank your very much for you thoughts, I needed to make a decision as to whether to 'go with the flow' or get rid of it altogether, and felt a little apprehensive about it after reading up on netplan on stackoverflow.

You input is reassuring and is much appreciated.

**Comment by erelson** [comment]
No problem. I was happy to revisit the reasons behind the change. It was a decision made largely in a vacuum, and perhaps I should share such planned approaches with the fetch_users google group in the future!
